POST http://127.0.0.1:8000/api/login
Content-Type: application/json

{ "username": "Destinne", "password": "Destinne" }

###

POST http://127.0.0.1:8000/api/signup
Content-Type: application/json

{ "username": "Destinne", "password": "Destinne", "email": "paynedestinne@gmail.com" }

###

GET http://127.0.0.1:8000/api/token
Content-Type: application/json
Authorization: Token 82cf370959795c75b52a094a28fad25fc498e593

{}

###
POST http://127.0.0.1:8000/api/performance/1/
Content-Type: application/json

{ "user": "Destinne", "subject": "English", "grade": "A" }

###

POST http://127.0.0.1:8000/api/signon
Content-Type: application/json

{ "username": "Meruaki", "email": "Meruaki123@gmail.com", "password": "Meruaki" }

###

POST http://127.0.0.1:8000/api/logon
Content-Type: application/json

{ "username": "Meruaki", "password": "Meruaki" }

###

GET http://127.0.0.1:8000/api/usercheck
Content-Type: application/json

{}