# Generated by Django 4.2.7 on 2023-11-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('paytask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paytask.student'),
        ),
    ]
