# Generated by Django 4.2.7 on 2023-11-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paytask', '0002_alter_performance_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='user',
            new_name='student',
        ),
    ]
