# Generated by Django 4.2.7 on 2023-11-15 08:58

from django.db import migrations, models
import uuid


def gen_uuid(apps, schema_editor):
    MyModel1 = apps.get_model("paytask", "Student")
    MyModel2 = apps.get_model("paytask", "Teacher")
    
    for row in MyModel1.objects.all():
        row.unique_code = uuid.uuid4()
        row.save(update_fields=["unique_code"])
        
    for row in MyModel2.objects.all():
        row.unique_code = uuid.uuid4()
        row.save(update_fields=["unique_code"])

class Migration(migrations.Migration):

    dependencies = [
        ('paytask', '0004_student_unique_code_teacher_unique_code'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
