# Generated by Django 4.2.7 on 2023-11-15 08:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('paytask', '0005_auto_20231115_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='unique_code',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='unique_code',
            field=models.CharField(default=uuid.uuid4, max_length=10, unique=True),
        ),
    ]
